### ISSUE TITLE
java.lang.NoSuchMethodError: No static method decodeHex(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)                                                                                    	

### ISSUE THREAD

**Issue by piyushyadavNP** [mvallim/emv-qrcode#52]
**Describe the bug**
java.lang.NoSuchMethodError: No static method decodeHex(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)
                                                                                                    	at com.emv.qrcode.core.model.cpm.BERTLBinary.toPrimitives(BERTLBinary.java:35)
                                                                                                    	at com.emv.qrcode.core.model.cpm.BERTLBinary.<init>(BERTLBinary.java:26)

**To Reproduce**
1. Downgrade API Level to 26

I am getting this error while targeting to android 8 and 8.1

**Comment by apkelly** [comment]
Android ships an old version of commons-codec internally, which is the one found before any libraries shipped with an app. Hence the error above. The fix is to not use commons-codec internally to convert Hex to String (or to use a method available on the really old version of commons-codec that is shipped with Android).
